# Generated by Django 5.2.3 on 2025-06-23 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Ide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('status', models.CharField(choices=[('Konsep', 'Konsep'), ('Pengembangan', 'Pengembangan'), ('Selesai', 'Selesai')], default='Konsep', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ide', to=settings.AUTH_USER_MODEL)),
                ('suka', models.ManyToManyField(blank=True, related_name='ide_disukai', to=settings.AUTH_USER_MODEL)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('ide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='core.ide')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
