# Generated by Django 5.2.3 on 2025-06-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ide',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='ide_pics'),
        ),
    ]
